#!/bin/bash

# All diretories in the home directory
DIRS=()
for FILE in /home/*; do
    if [[ -d $FILE ]]; then
        DIRS+=( "$FILE" )
        echo $FILE
    fi
done

# Create directory structure
for studentDIR in "${DIRS[@]}"; do
  # Making directories and chmoding them for the scenario
  mkdir /$studentDIR/door
done

rm -r /root/scenario-dungeon-crawler
